// Demo mock data — mirrors seed.sql exactly. No DB calls.

export const MOCK_PERSON = {
  id: 'demo-darshit',
  name: 'Darshit Raut',
  email: 'darshit@ampmnetwork.com',
  role: "Founders Office",
  department: 'Ops',
  is_team_lead: true,
};

export const MOCK_BRANDS = [
  {
    id: 'brand-1',
    slug: 'indiagate',
    name: 'IndiaGate',
    category: 'FMCG — Basmati Rice',
    tier: 'tier-1',
    status: 'active',
    colors: { primary: '#1A3C6E', secondary: '#D4AF37', accent: '#FFFFFF', warm: '#F5E6C8' },
    voice_summary: 'Premium, heritage, trusted. Rooted in India — national, not regional. Never cheap or pushy. Speaks to the homemaker who takes cooking seriously. Warmth first, aspiration second. Short sentences. No exclamation marks.',
    typography: { display: 'Playfair Display', body: 'Lato', labels: 'Montserrat' },
  },
  {
    id: 'brand-2',
    slug: 'truesilver',
    name: 'TrueSilver',
    category: 'Jewellery',
    tier: 'tier-2',
    status: 'active',
    colors: { primary: '#2C2C2C', secondary: '#C0C0C0', accent: '#F8F8F8' },
    voice_summary: 'Refined, understated luxury. Every word earns its place. The product speaks — copy supports it quietly. No hyperbole.',
    typography: { display: 'Cormorant Garamond', body: 'Inter', labels: 'Montserrat' },
  },
  {
    id: 'brand-3',
    slug: 'alphakid',
    name: 'AlphaKid',
    category: 'Kids',
    tier: 'tier-2',
    status: 'active',
    colors: { primary: '#FF6B35', secondary: '#FFD700', accent: '#4CAF50', bg: '#FFF9F0' },
    voice_summary: 'Bold, playful, energetic. Speaks to both parent and child. Fun-forward but builds trust with parents. Short punchy copy. Action verbs. Bright tone.',
    typography: { display: 'Nunito', body: 'Quicksand', labels: 'Nunito' },
  },
  {
    id: 'brand-4',
    slug: 'vadilal',
    name: 'Vadilal',
    category: 'FMCG — Ice Cream / Dairy',
    tier: 'tier-2',
    status: 'active',
    colors: { primary: '#E91E8C', secondary: '#FFC107', accent: '#FFFFFF', dark: '#1A1A1A' },
    voice_summary: 'Joyful, nostalgic, celebratory. India\'s summer. Family moments. Copy should feel like a smile. Warm and inclusive — everyone belongs here.',
    typography: { display: 'Poppins', body: 'Poppins', labels: 'Roboto Mono' },
  },
];

export const MOCK_PEOPLE = [
  { id: 'p-darshit',  name: 'Darshit Raut',        department: 'Ops' },
  { id: 'p-shivangi', name: 'Shivangi Shekhar',     department: 'Leadership' },
  { id: 'p-trupti',   name: 'Trupti Maidh',         department: 'Account' },
  { id: 'p-pierre',   name: 'Pierre Santos',         department: 'Creative' },
  { id: 'p-pratik',   name: 'Pratik Kshirsagar',    department: 'Creative' },
  { id: 'p-manan',    name: 'Manan Shah',            department: 'Creative' },
  { id: 'p-kuldip',   name: 'Kuldip Mankar',         department: 'Creative' },
  { id: 'p-yashika',  name: 'Yashika Mistry',        department: 'Creative' },
  { id: 'p-nimesh',   name: 'Nimesh Shinde',         department: 'Video' },
  { id: 'p-vineet',   name: 'Vineet Shelar',         department: 'Video' },
  { id: 'p-tarun',    name: 'Tarun',                 department: 'Video' },
  { id: 'p-aman',     name: 'Aman Adodra',           department: 'SEO' },
  { id: 'p-dhwani',   name: 'Dhwani Chhelavda',      department: 'Content' },
  { id: 'p-muskaan',  name: 'Muskaan Madnani',       department: 'Sales' },
  { id: 'p-moksha',   name: 'Moksha Mehta',          department: 'Sales' },
  { id: 'p-shivani',  name: 'Shivani Reshamwala',    department: 'Sales' },
  { id: 'p-rajat',    name: 'Rajat Dey',             department: 'Marketing' },
  { id: 'p-shawn',    name: 'Shawn Dsouza',          department: 'Marketing' },
  { id: 'p-shanvi',   name: 'Shanvi Patel',          department: 'Marketing' },
  { id: 'p-yassha',   name: 'Yassha Gada',           department: 'Marketing' },
];

export const MOCK_TASKS = [
  {
    id: 'task-1',
    deliverable: 'IndiaGate Diwali Campaign — 3 Reels',
    task_type: 'video',
    priority: 'P0',
    status: 'in_progress',
    estimated_hours: 6,
    deadline: new Date(Date.now() + 2 * 86400000).toISOString(),
    meeting_id: null,
    owner_id: 'p-vineet',
    brands: { name: 'IndiaGate' },
    owner: { name: 'Vineet Shelar' },
    references: [
      { id: 'r1', ref_type: 'figma', url: 'https://figma.com/demo', caption: 'Mood Board v2' },
    ],
  },
  {
    id: 'task-2',
    deliverable: 'TrueSilver Product Catalogue — Q4',
    task_type: 'design',
    priority: 'P1',
    status: 'scheduled',
    estimated_hours: 4,
    deadline: new Date(Date.now() + 4 * 86400000).toISOString(),
    meeting_id: null,
    owner_id: 'p-pratik',
    brands: { name: 'TrueSilver' },
    owner: { name: 'Pratik Kshirsagar' },
    references: [],
  },
  {
    id: 'task-3',
    deliverable: 'AlphaKid YouTube Pre-roll Script',
    task_type: 'copy',
    priority: 'P1',
    status: 'ready_for_review',
    estimated_hours: 2,
    deadline: new Date(Date.now() + 1 * 86400000).toISOString(),
    meeting_id: null,
    owner_id: 'p-manan',
    brands: { name: 'AlphaKid' },
    owner: { name: 'Manan Shah' },
    references: [
      { id: 'r2', ref_type: 'reference', url: 'https://youtube.com/demo', caption: 'Reference Ad' },
    ],
  },
  {
    id: 'task-4',
    deliverable: 'Vadilal Summer Social — 10 posts',
    task_type: 'content',
    priority: 'P2',
    status: 'scheduled',
    estimated_hours: 5,
    deadline: new Date(Date.now() + 6 * 86400000).toISOString(),
    meeting_id: null,
    owner_id: 'p-dhwani',
    brands: { name: 'Vadilal' },
    owner: { name: 'Dhwani Chhelavda' },
    references: [],
  },
  {
    id: 'task-5',
    deliverable: 'IndiaGate SEO Blog — Basmati Rice Guide',
    task_type: 'seo',
    priority: 'P1',
    status: 'approved',
    estimated_hours: 3,
    deadline: new Date(Date.now() - 1 * 86400000).toISOString(),
    meeting_id: 'meeting-1',
    owner_id: 'p-aman',
    brands: { name: 'IndiaGate' },
    owner: { name: 'Aman Adodra' },
    references: [],
  },
];

export const MOCK_BLOCKS = [
  {
    id: 'block-1',
    start_at: (() => { const d = new Date(); d.setHours(10, 0, 0, 0); return d.toISOString(); })(),
    end_at: (() => { const d = new Date(); d.setHours(16, 0, 0, 0); return d.toISOString(); })(),
    status: 'in_progress',
    actual_hours: null,
    tasks: {
      id: 'task-1',
      deliverable: 'IndiaGate Diwali Campaign — 3 Reels',
      task_type: 'video',
      priority: 'P0',
      estimated_hours: 6,
      notes: 'Focus on the heritage angle. Use the gold/navy palette. No talking heads.',
      status: 'in_progress',
      owner_id: 'demo-darshit',
      reviewer_id: 'demo-pierre',
      brands: {
        id: 'brand-1',
        slug: 'indiagate',
        name: 'IndiaGate',
        colors: { primary: '#1A3C6E', secondary: '#D4AF37', accent: '#FFFFFF', warm: '#F5E6C8' },
        typography: {},
        voice_summary: 'Premium, heritage, trusted. Warmth first, aspiration second. Short sentences. No exclamation marks.',
      },
      owner: { id: 'demo-darshit', name: 'Darshit Raut' },
      reviewer: { id: 'demo-pierre', name: 'Pierre Santos' },
      references: [
        { id: 'r1', ref_type: 'figma', url: 'https://figma.com/demo', caption: 'Mood Board v2' },
        { id: 'r2', ref_type: 'miro', url: 'https://miro.com/demo', caption: 'Storyboard Draft' },
      ],
    },
  },
  {
    id: 'block-2',
    start_at: (() => { const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(10, 0, 0, 0); return d.toISOString(); })(),
    end_at: (() => { const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(14, 0, 0, 0); return d.toISOString(); })(),
    status: 'scheduled',
    actual_hours: null,
    tasks: {
      id: 'task-3',
      deliverable: 'AlphaKid YouTube Pre-roll Script',
      task_type: 'copy',
      priority: 'P1',
      estimated_hours: 4,
      notes: null,
      status: 'scheduled',
      owner_id: 'demo-darshit',
      reviewer_id: null,
      brands: {
        id: 'brand-3',
        slug: 'alphakid',
        name: 'AlphaKid',
        colors: { primary: '#FF6B35', secondary: '#FFD700', accent: '#4CAF50', bg: '#FFF9F0' },
        typography: {},
        voice_summary: 'Bold, playful, energetic. Fun-forward but builds trust with parents. Short punchy copy. Action verbs.',
      },
      owner: { id: 'demo-darshit', name: 'Darshit Raut' },
      reviewer: null,
      references: [
        { id: 'r3', ref_type: 'reference', url: 'https://youtube.com/demo', caption: 'Reference Ad' },
      ],
    },
  },
];
